In [1]:
import numpy as np

### Stationary Distribution π

In [2]:
A = np.array([
    [0.1, 0.4, 0.3, 0.2],
    [0.1, 0.4, 0.3, 0.2],
    [0.0, 0.1, 0.4, 0.5],
    [0.0, 0.0, 0.1, 0.9]
])

#### Brute force approx.

In [18]:
n= 100000
A_n= A
for i in range(n):
    A_n = np.dot(A_n,A)

print(A_n)

[[0.0030303  0.02727273 0.15151515 0.81818182]
 [0.0030303  0.02727273 0.15151515 0.81818182]
 [0.0030303  0.02727273 0.15151515 0.81818182]
 [0.0030303  0.02727273 0.15151515 0.81818182]]


#### approx. via eigen value decomposition

In [19]:
eigenvalues, P_vectors = np.linalg.eig(A.T)
# print(np.isclose(eigenvalues, 1).any()) #verification
id = np.argmin(np.abs(eigenvalues - 1))
eigenvalues, P_vectors, id

(array([ 1.00000000e+00,  5.73205081e-01, -4.30037190e-17,  2.26794919e-01]),
 array([[-3.63980654e-03, -8.46457535e-02, -7.07106781e-01,
          1.33119590e-01],
        [-3.27582588e-02, -4.00548006e-01,  7.07106781e-01,
          1.68788877e-01],
        [-1.81990327e-01, -3.55186484e-01, -1.75319589e-16,
         -8.24829269e-01],
        [-9.82747765e-01,  8.40380243e-01,  1.05508493e-16,
          5.22920803e-01]]),
 0)

In [20]:
pi= np.real(P_vectors[:, id])
pi/= pi.sum()
pi

array([0.0030303 , 0.02727273, 0.15151515, 0.81818182])

$$
(A^T)^n = P D^n P^{-1} \iff A^n = (P D^n P^{-1})^T
$$

In [21]:
eigenvalues, eigenvectors = np.linalg.eig(A)
P = eigenvectors
D = np.diag(eigenvalues)

P_inv = np.linalg.inv(P)

n = 10**5

D_n = np.diag(eigenvalues**n)

A_n = P @ D_n @ P_inv

In [22]:
A_n

array([[0.0030303 , 0.02727273, 0.15151515, 0.81818182],
       [0.0030303 , 0.02727273, 0.15151515, 0.81818182],
       [0.0030303 , 0.02727273, 0.15151515, 0.81818182],
       [0.0030303 , 0.02727273, 0.15151515, 0.81818182]])

### constrained linear system resolution 

In [24]:
def compute_pi(A):

    n = A.shape[0]  
    A = np.transpose(A) - np.eye(n)  

    A[-1, :] = 1

    b = np.zeros(n)
    b[-1] = 1  #sum(pi) = 1

    pi = np.linalg.solve(A, b) # A * pi = b
    return pi


In [25]:
compute_pi(A)

array([0.0030303 , 0.02727273, 0.15151515, 0.81818182])

### MC simulation

In [29]:
def sample_chain(n, x_0):

    states = np.zeros(n, dtype=int)
    states[0] = x_0
    
    for i in range(1, n):
        current_state = states[i-1]
        states[i] = np.random.choice([0, 1, 2, 3], p=A[current_state])

    return states

sample_chain(n=10, x_0=0)

array([0, 1, 0, 0, 2, 3, 3, 3, 3, 3])

### Ergodicity (irreductible nd aperiodic chain)